/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfigurationIndexRouteImport } from './routes/configuration/index'

const ConfigurationIndexRoute = ConfigurationIndexRouteImport.update({
  id: '/configuration/',
  path: '/configuration/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/configuration': typeof ConfigurationIndexRoute
}
export interface FileRoutesByTo {
  '/configuration': typeof ConfigurationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/configuration/': typeof ConfigurationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/configuration'
  fileRoutesByTo: FileRoutesByTo
  to: '/configuration'
  id: '__root__' | '/configuration/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConfigurationIndexRoute: typeof ConfigurationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/configuration/': {
      id: '/configuration/'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ConfigurationIndexRoute: ConfigurationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
