/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecordingStatusRouteImport } from './routes/recording-status'
import { Route as ConfigurationRouteImport } from './routes/configuration'
import { Route as CaptureNoteRouteImport } from './routes/capture-note'

const RecordingStatusRoute = RecordingStatusRouteImport.update({
  id: '/recording-status',
  path: '/recording-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationRoute = ConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureNoteRoute = CaptureNoteRouteImport.update({
  id: '/capture-note',
  path: '/capture-note',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/capture-note': typeof CaptureNoteRoute
  '/configuration': typeof ConfigurationRoute
  '/recording-status': typeof RecordingStatusRoute
}
export interface FileRoutesByTo {
  '/capture-note': typeof CaptureNoteRoute
  '/configuration': typeof ConfigurationRoute
  '/recording-status': typeof RecordingStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/capture-note': typeof CaptureNoteRoute
  '/configuration': typeof ConfigurationRoute
  '/recording-status': typeof RecordingStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/capture-note' | '/configuration' | '/recording-status'
  fileRoutesByTo: FileRoutesByTo
  to: '/capture-note' | '/configuration' | '/recording-status'
  id: '__root__' | '/capture-note' | '/configuration' | '/recording-status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CaptureNoteRoute: typeof CaptureNoteRoute
  ConfigurationRoute: typeof ConfigurationRoute
  RecordingStatusRoute: typeof RecordingStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recording-status': {
      id: '/recording-status'
      path: '/recording-status'
      fullPath: '/recording-status'
      preLoaderRoute: typeof RecordingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration': {
      id: '/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof ConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture-note': {
      id: '/capture-note'
      path: '/capture-note'
      fullPath: '/capture-note'
      preLoaderRoute: typeof CaptureNoteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CaptureNoteRoute: CaptureNoteRoute,
  ConfigurationRoute: ConfigurationRoute,
  RecordingStatusRoute: RecordingStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
